### ISSUE TITLE
Financials: Data Collection

### ISSUE THREAD

**Issue by daniamohamed** [group-geopulse/GeoPulse#10]
#### Description  
Collecting financial data from yfinance. Ensure all fields necessary are being imported. Explore the variety of metrics present in the yfinance dataset or if there's a better alternative. Fetch, clean, and format the data into JSON-like storage for later use.  

#### Tasks  
- [x] Select suitable tickers, time period for required data from yfinance.
- [x] Collect data from yfinance and store in suitable data format.
- [x] Explore data and filter to only keep relevant columns.
- [x] Consider how this will be automated to update the script, or update database directly.

#### Prerequisites  
None.
